# Generated by Django 4.2.4 on 2026-02-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("GUILTY", "Guilty (Convicted)"),
                            ("INNOCENT", "Innocent (Acquitted)"),
                        ],
                        default="INNOCENT",
                        max_length=20,
                    ),
                ),
                (
                    "sentence_type",
                    models.CharField(
                        choices=[
                            ("NONE", "None (Innocent)"),
                            ("PRISON", "Imprisonment"),
                            ("FINE", "Fine Penalty"),
                            ("PRISON_AND_FINE", "Prison & Fine"),
                            ("COMMUNITY", "Community Service"),
                            ("EXECUTION", "Death Penalty"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "prison_months",
                    models.PositiveIntegerField(
                        default=0, help_text="Duration in months (if applicable)"
                    ),
                ),
                (
                    "fine_amount",
                    models.BigIntegerField(
                        default=0, help_text="Amount in Rials (if applicable)"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., '1st Degree Murder Conviction'", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Full text of the sentencing"),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interrogation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="court_verdict",
                        to="investigation.interrogation",
                    ),
                ),
                (
                    "judge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issued_verdicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
