# Generated by Django 4.2.4 on 2026-02-21 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reward",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="reward",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.case",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="amount",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="reward",
            name="citizen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_tips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="reward",
            name="detective_approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_tips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="officer_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_tips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Officer Review"),
                    ("FORWARDED", "Forwarded to Detective"),
                    ("APPROVED", "Approved by Detective"),
                    ("REJECTED", "Rejected"),
                    ("PAID", "Reward Paid"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="suspect",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="investigation.suspect",
            ),
        ),
        migrations.AlterField(
            model_name="reward",
            name="unique_tracking_id",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ReleaseRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Sergeant Review"),
                            ("APPROVED", "Approved (Amounts Set)"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid and Released"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "bail_amount",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Set by Sergeant for Suspects (Level 2/3)",
                        null=True,
                    ),
                ),
                (
                    "fine_amount",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Set by Sergeant for Criminals (Level 3)",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "interrogation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_requests",
                        to="investigation.interrogation",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sergeant_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_releases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
