# Generated by Django 4.2.4 on 2026-02-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "crime_level",
                    models.IntegerField(
                        choices=[
                            (1, "Level 3 – Minor (e.g. petty theft)"),
                            (2, "Level 2 – Major (e.g. car theft)"),
                            (3, "Level 1 – Serious (e.g. murder)"),
                            (4, "Critical (e.g. serial murder / assassination)"),
                        ]
                    ),
                ),
                (
                    "formation_type",
                    models.CharField(
                        choices=[
                            ("COMPLAINT", "Formed via Complaint"),
                            ("CRIME_SCENE", "Formed via Crime Scene Report"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_CADET_REVIEW", "Pending Cadet Review"),
                            ("RETURNED_TO_COMPLAINANT", "Returned to Complainant"),
                            ("RETURNED_TO_CADET", "Returned to Cadet (by Officer)"),
                            ("PENDING_OFFICER_REVIEW", "Pending Officer Review"),
                            ("PENDING_SUPERIOR_APPROVAL", "Pending Superior Approval"),
                            ("VOIDED", "Voided (Complainant 3× rejected)"),
                            ("OPEN", "Open"),
                            ("INVESTIGATION", "Under Investigation (Detective Board)"),
                            ("WAITING_FOR_SERGEANT", "Waiting for Sergeant Approval"),
                            ("INTERROGATION", "Suspects Arrested & Interrogating"),
                            ("WAITING_FOR_CAPTAIN", "Waiting for Captain Verdict"),
                            (
                                "WAITING_FOR_CHIEF",
                                "Waiting for Chief of Police (Critical)",
                            ),
                            ("IN_COURT", "Sent to Court (Judge Review)"),
                            ("CLOSED_VERDICT", "Closed – Verdict Given"),
                            (
                                "CLOSED_REJECTED",
                                "Closed – Rejected by Police Hierarchy",
                            ),
                        ],
                        db_index=True,
                        default="PENDING_CADET_REVIEW",
                        max_length=40,
                    ),
                ),
                (
                    "complainant_rejection_count",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("crime_occurred_at", models.DateTimeField(blank=True, null=True)),
                ("crime_scene_location", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_detective",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detective_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_sergeant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sergeant_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_complainant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="primary_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseWitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_id", models.CharField(max_length=20)),
                ("phone_number", models.CharField(max_length=15)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="cases.case",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_witnesses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["registered_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=40)),
                ("to_status", models.CharField(max_length=40)),
                ("message", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="cases.case",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseComplainant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Cadet Review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("rejection_note", models.TextField(blank=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complainants",
                        to="cases.case",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="complainant_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_complainants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["added_at"],
                "unique_together": {("case", "user")},
            },
        ),
    ]
