# Generated by Django 4.2.4 on 2026-02-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySystemStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("new_cases_count", models.PositiveIntegerField(default=0)),
                ("closed_cases_count", models.PositiveIntegerField(default=0)),
                ("total_active_cases", models.PositiveIntegerField(default=0)),
                (
                    "total_rewards_paid",
                    models.BigIntegerField(default=0, help_text="in Rials"),
                ),
                (
                    "total_payments_received",
                    models.BigIntegerField(default=0, help_text="in Rials"),
                ),
                ("avg_resolution_time_hours", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Daily System Statistic",
                "ordering": ["-date"],
            },
        ),
    ]
