# Generated by Django 4.2.4 on 2026-02-20 20:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evidence", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        help_text="Name or description if not a registered user",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNDER_SURVEILLANCE", "Under Surveillance"),
                            ("MOST_WANTED", "Most Wanted (>30 days open)"),
                            ("ARRESTED", "Arrested"),
                            ("RELEASED_ON_BAIL", "Released on Bail"),
                            ("CONVICTED", "Convicted"),
                            ("ACQUITTED", "Acquitted"),
                        ],
                        db_index=True,
                        default="UNDER_SURVEILLANCE",
                        max_length=20,
                    ),
                ),
                (
                    "cached_ranking_score",
                    models.BigIntegerField(db_index=True, default=0),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criminal_record",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note_text", models.TextField(blank=True, null=True)),
                ("x_position", models.FloatField(default=0.0)),
                ("y_position", models.FloatField(default=0.0)),
                ("color", models.CharField(default="#ffeb3b", max_length=20)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="board_nodes",
                        to="cases.case",
                    ),
                ),
                (
                    "linked_evidence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evidence.evidence",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoardConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(default="red", max_length=20)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cases.case"
                    ),
                ),
                (
                    "from_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="investigation.boardnode",
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="investigation.boardnode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Interrogation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detective_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Guilt probability (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "sergeant_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("sergeant_approval", models.BooleanField(blank=True, null=True)),
                ("sergeant_notes", models.TextField(blank=True)),
                ("captain_verdict", models.BooleanField(blank=True, null=True)),
                ("chief_verdict", models.BooleanField(blank=True, null=True)),
                (
                    "bail_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Set by Sergeant",
                        max_digits=15,
                        null=True,
                    ),
                ),
                ("is_released_on_bail", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interrogations",
                        to="cases.case",
                    ),
                ),
                (
                    "suspect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interrogations",
                        to="investigation.suspect",
                    ),
                ),
            ],
            options={
                "unique_together": {("case", "suspect")},
            },
        ),
    ]
