# Generated by Django 4.2.4 on 2026-02-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investigation", "0003_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="boardnode",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
