# Generated by Django 4.2.4 on 2026-02-20 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("WITNESS", "Witness Testimony/Media"),
                            ("BIO", "Biological/Medical"),
                            ("VEHICLE", "Vehicle"),
                            ("ID", "Identification Document"),
                            ("MISC", "Miscellaneous"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_list",
                        to="cases.case",
                    ),
                ),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BioEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evidence.evidence",
                    ),
                ),
                (
                    "bio_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood Sample"),
                            ("DNA", "DNA / Hair"),
                            ("FINGERPRINT", "Fingerprint"),
                            ("OTHER", "Other Biological"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coroner_verification",
                    models.TextField(
                        blank=True,
                        help_text="Results from the Coroner or Identity Database",
                        null=True,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_bio_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("evidence.evidence",),
        ),
        migrations.CreateModel(
            name="IDEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evidence.evidence",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(help_text="Name on the document", max_length=200),
                ),
                ("document_data", models.JSONField(blank=True, default=dict)),
            ],
            bases=("evidence.evidence",),
        ),
        migrations.CreateModel(
            name="MiscEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evidence.evidence",
                    ),
                ),
            ],
            bases=("evidence.evidence",),
        ),
        migrations.CreateModel(
            name="VehicleEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evidence.evidence",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=50)),
                (
                    "plate_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        help_text="VIN / Chassis Number",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            bases=("evidence.evidence",),
        ),
        migrations.CreateModel(
            name="WitnessEvidence",
            fields=[
                (
                    "evidence_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="evidence.evidence",
                    ),
                ),
                (
                    "transcript",
                    models.TextField(
                        blank=True, help_text="Written transcript of the testimony"
                    ),
                ),
                (
                    "media_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to audio/video/image file",
                        null=True,
                    ),
                ),
                (
                    "linked_witness",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="formal_statements",
                        to="cases.casewitness",
                    ),
                ),
            ],
            bases=("evidence.evidence",),
        ),
        migrations.CreateModel(
            name="BioEvidenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(help_text="URL to the image file")),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Close up of the stain'",
                        max_length=100,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="evidence.bioevidence",
                    ),
                ),
            ],
        ),
    ]
